### ISSUE TITLE
What is an event?

### ISSUE THREAD

**Issue by jsm13** [ga-wdi-lessons/js-events-callbacks#9]
After having researched JS events, (1) include a link to any resource(s) you found valuable, (2) in **your own words**, define event, and (3. a-c) give 3 examples of events.

When you have finished, check out some of the other responses and resources.

**Comment by edawson1980** [comment]
1) valuable resource:   https://www.w3schools.com/js/js_events.asp

2) an event is acting upon a page to create a real-time reaction

3) examples would include:  clicking a  button, submitting a form, pushing a certain keyboard key.

**Comment by Costle784** [comment]
https://www.w3schools.com/js/js_htmldom_eventlistener.asp

An event in javascript is a DOM method that 'listens' for a particular thing to occur, then executes a set function when it's detected.
ex. click, mouseover, submit

**Comment by electricflannel** [comment]
1. An event is where something that triggers a function call
2. An event can be something the browser does, or something a user does
3. .click() .mouseover() .ready()

**Comment by wjpurdum** [comment]
**1. Come up with your own definition without looking at any other sources. Don't worry about getting it right -- what do you think an event is?**
An event is something that happens to the DOM (to the html or text on the page) that triggers a functionality. For example, someone clicks on a link or hovers over an image, and this triggers code that has not yet run. 

**Now, find (i.e., Google) some documentation on Javascript events. Does that information match your definition? How would you update your definition to include what you have learned but rephrased in your own words?**
Yes, 

**Write down three examples of events.**
1. onhover
2. animationend
3. onerror

**Comment by twelve13** [comment]
1.  An event is an action or set of actions that occurs at a particular time.
2. MDN says events are notifications to code that something has taken place.
3. Examples:
    a. Button was clicked
    b. Web page finished loading
    c. A key is pressed

**Comment by meagdoh** [comment]
An event is a reaction to changes/clicks on a page (e.g. when I click on the "Sign Up" button, a sign-up prompt appears)

MDN and W3Schools are good resources

**Comment by cconnerj** [comment]
1. Resource: https://www.w3schools.com/js/js_events.asp
2. Events are actions the browser does when the user interacts with a webpage
3. Onload, onclick, onchange

**Comment by pchristianbrown** [comment]
Event-the triggering program  or code that prompts the application to interact with the website.
Keystrokes
hyperlink
animation/video starting

**Comment by lgmusic24** [comment]
Event is the occurrence of the action when the function is executed.

**Comment by mattpcaplan** [comment]
1. (My personal definition - no lookup): An event listens for something to occur.  It then executes a command
2. https://www.w3schools.com/js/js_events.asp
3. onkeydown , onclick , onmouseover

**Comment by kwonih1020** [comment]
1. An event is something just happens.
2.An event is something that user, or webpage does.
3. input, mouse, load.

**Comment by StormyRamsey** [comment]
A JS event occurs when some type of action takes place on a webpage, such as clicking a button, refreshing a page or adding information to an input box. 

https://www.w3schools.com/js/js_events.asp

**Comment by zonekid** [comment]
https://www.w3schools.com/js/js_events.asp

2. An event is a type of code that helps make elements do certain actions based on user input that matches that action. Such as reacting if a button is clicked etc.

3. Ex. Clicking a button, onmouseover, (when your mouse runs over a certain area) onkeydown

**Comment by ammaralasadi1** [comment]
An event is a trigger for an action. Example: 

element.addEventListener("click", function(){ alert("Hello World!"); });

Source w3schools.com

**Comment by jkoo87** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Event
-An event triggers the webpage to do interest things, such as page loading, clicking, and submitting.

**Comment by o0c91047** [comment]
according to w3schools https://www.w3schools.com/js/js_events.asp:

An event sets a trigger for something to occur by either a user or the webpage

mouseover, onclick, onload

**Comment by amlakgirma** [comment]
1.Event is action that need input and result output.

**Comment by utamilah** [comment]
(1) include a link to any resource: [Events Reference](https://developer.mozilla.org/en-US/docs/Web/Events)
(2) An event is a way to trigger something to happen
(3) Examples of Events:
  (a) onclick
  (b) mouseenter
  (c) mouseover

**Comment by daniellefricke** [comment]
1. An event is something that calls a function once a webpage is open.
2. An event can be something the browser does, or something a user does.
3. onclick, onmouseover, onsubmit

**Comment by scottpiercew** [comment]
1. An event is an actionable item initiated by a trigger.
2. An event is JavaScript’s interaction with HTML and is initiated when the user or browser manipulates a page. 
3. onchange, onclick, onmouseover

**Comment by Fitssum** [comment]
1. Events are user’s initiated action to interact with the website.
2. JavaScript's interaction with HTML is handled through events that occur when the user or the browser manipulates a page. When the page loads, it is called an event. 
3. onblur, onselect, onsubmit

**Comment by tedlayea** [comment]
Event is action from the user whether using keyboard or mouse that triggers some functionality.
Events is when there is action that occurred on DOM based on the user response. 
Example of event: onmouseout, onload, onmouseover

**Comment by usmanahmed090** [comment]
1. an event is a functionality when a user initiates something.
2. DOM Events are interaction by user that manipulates the page
3.onchange onclick onmouseover
